### ISSUE TITLE
UX Design Implementation Landing Page

### ISSUE THREAD

**Issue by Natanta94** [people-eat/people-eat#37]

**Comment by Natanta94** [comment]
- [ ] Anmelden Button - desktop - discuss with Irina
- [ ] Define order or scrolls (occasions/bekannt durch part) - Natalia/Daniel
- [ ] Find out why some pictures not uploaded
- [ ] Add footer
- [ ] Add cities
- [ ] Change text font

**Comment by CemYil03** [comment]
# Feedback

## Header

- Mobile - Login / Profile button design needed (important - should not disappear on background)
- Desktop - Hover state for sign in button

## Section 1

- update Video
- video alternative text
- video file name
- change text

## Section 2

-

**Comment by Natanta94** [comment]
Alt Texten:

Scroll #1: 
Video: Eine Familie feiert einen besonderen Anlass zu Hause mit einem Privatkoch.

Scroll #2:
Casual Dining: Mädchen sitzen gemeinsam an einem Tisch mit Kerzen und genießen ein Abendessen.
Signature menu: Ein Paar genießt ein Candle-Light-Dinner, zubereitet von einem Spitzenkoch.
Unvergessliches Geschenk: Eine Gutscheinkarte von PeopleEat für ein Dinner mit einem Privatkoch.
